/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_renyushuang_ryscrius_JniHelloWord */

JNIEXPORT jstring JNICALL
Java_crius_jni_JniHelloWord_getNewString
        (JNIEnv *env, jobject thiz) {
    return (*env)->NewStringUTF(env, "hello word");
}
