/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class crius_jni_CallJavaMethodFromNativeCode */

/*
 * Class:     crius_jni_CallJavaMethodFromNativeCode
 * Method:    nativeInit
 * Signature: ()V
 */

jobject mObject;
jclass mClass;
jmethodID mJMethodID;
jmethodID mJStaticMethodID;

JNIEXPORT void JNICALL Java_crius_jni_CallJavaMethodFromNativeCode_nativeInit
        (JNIEnv *env, jobject thiz) {

    jclass clazz = (*env)->GetObjectClass(env, thiz);
    mClass = (*env)->NewGlobalRef(env, clazz);
    mObject = (*env)->NewGlobalRef(env, thiz);

    mJMethodID = (*env)->GetMethodID(env, clazz, "setMethodByNativeCode", "(I)V");
    mJStaticMethodID = (*env)->GetStaticMethodID(env, clazz, "setStaticMethodByNativeCode", "(I)V");
}

/*
 * Class:     crius_jni_CallJavaMethodFromNativeCode
 * Method:    nativeExecution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crius_jni_CallJavaMethodFromNativeCode_nativeExecution
        (JNIEnv *env, jobject thiz) {

    (*env)->CallVoidMethod(env, mObject, mJMethodID, 100);
}

/*
 * Class:     crius_jni_CallJavaMethodFromNativeCode
 * Method:    nativeStaticExcution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crius_jni_CallJavaMethodFromNativeCode_nativeStaticExcution
        (JNIEnv *env, jobject thiz) {
    (*env)->CallStaticVoidMethod(env, mClass, mJStaticMethodID, 100);
}

