/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"


jobject mObject;
jclass mClass;
jmethodID mJMethodID;
jmethodID mJStaticMethodID;
jfieldID mJFieldId;
/*
 * Class:     crius_jni_GetJavaPropertyFromNativeC
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crius_jni_GetJavaPropertyFromNativeC_nativeInit
        (JNIEnv *env, jobject thiz) {
    jclass clazz = (*env)->GetObjectClass(env, thiz);
    mClass = (*env)->NewGlobalRef(env, clazz);
    mObject = (*env)->NewGlobalRef(env, thiz);
    // 获取java对象中的变量id
    mJFieldId = (*env)->GetFieldID(env, clazz, "numberInJava", "I");
}

/*
 * Class:     crius_jni_GetJavaPropertyFromNativeC
 * Method:    nativeBusiness
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crius_jni_GetJavaPropertyFromNativeC_nativeBusiness
        (JNIEnv *env, jobject thiz) {
    // 获取java对象中的值
    int numberInJava = (*env)->GetIntField(env, mObject, mJFieldId);
}

