/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_renyushuang_ryscrius_JniHelloWord.h"
/* Header for class com_renyushuang_ryscrius_JniHelloWord */

JNIEXPORT jstring JNICALL
Java_com_renyushuang_ryscrius_JniHelloWord_getNewString
        (JNIEnv *env, jobject thiz) {
    return (*env)->NewStringUTF(env, "hello word");
}
