/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_renyushuang_ryscrius_JniHelloWord */

#ifndef _Included_com_renyushuang_ryscrius_JniHelloWord
#define _Included_com_renyushuang_ryscrius_JniHelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_renyushuang_ryscrius_JniHelloWord
 * Method:    getNewString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_renyushuang_ryscrius_JniHelloWord_getNewString
        (JNIEnv *, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
